# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-02 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='email',
            field=models.EmailField(default=b'Enter Email here', max_length=254),
        ),
        migrations.AddField(
            model_name='information',
            name='info',
            field=models.CharField(default=b'Enter Description about book ', max_length=300),
        ),
        migrations.AddField(
            model_name='information',
            name='mobile',
            field=models.CharField(default=b'Enter Mobile Number here', max_length=10),
        ),
        migrations.AddField(
            model_name='information',
            name='name',
            field=models.CharField(default=b'Enter Full Name here', max_length=100),
        ),
    ]
