# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-02 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20170703_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='cost',
            field=models.CharField(default='Enter Cost of the book ', max_length=4),
        ),
    ]
